/**
 * Domain Enums for PreScan Platform Foundation
 * Standard TypeScript Enums
 */

export enum MembershipRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
  EDITOR = 'EDITOR',
  VIEWER = 'VIEWER',
}

export enum RiskLevel {
  LOW = 'LOW',                     // Green - Low risk / positive
  REVIEW_REQUIRED = 'REVIEW_REQUIRED', // Yellow - Review required
  IMPORTANT = 'IMPORTANT',         // Red - Important review
  INSUFFICIENT_DATA = 'INSUFFICIENT_DATA', // Gray - Not analyzed / insufficient
}

export enum FindingCategory {
  COMMUNITY_GUIDELINES = 'COMMUNITY_GUIDELINES',
  ADVERTISER_SUITABILITY = 'ADVERTISER_SUITABILITY',
  COPYRIGHT_SIGNALS = 'COPYRIGHT_SIGNALS',
  METADATA_INTEGRITY = 'METADATA_INTEGRITY',
}

export enum ScanStatus {
  DRAFT = 'DRAFT',
  QUEUED = 'QUEUED',
  VALIDATING = 'VALIDATING',
  FETCHING_METADATA = 'FETCHING_METADATA',
  ACQUIRING_MEDIA = 'ACQUIRING_MEDIA',
  EXTRACTING_AUDIO = 'EXTRACTING_AUDIO',
  TRANSCRIBING = 'TRANSCRIBING',
  ANALYZING = 'ANALYZING',
  VALIDATING_REPORT = 'VALIDATING_REPORT',
  INGESTING = 'INGESTING',
  READY_FOR_ANALYSIS = 'READY_FOR_ANALYSIS',
  PROCESSING = 'PROCESSING',
  ANALYZING_AUDIO = 'ANALYZING_AUDIO',
  ANALYZING_METADATA = 'ANALYZING_METADATA',
  GENERATING_REPORT = 'GENERATING_REPORT',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum PlanTier {
  FREE = 'FREE',
  CREATOR = 'CREATOR',
  PRO = 'PRO',
  STUDIO = 'STUDIO',
  ENTERPRISE = 'ENTERPRISE',
}

export enum SubscriptionStatus {
  INACTIVE = 'INACTIVE',
  TRIALING = 'TRIALING',
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  CANCELED = 'CANCELED',
  UNPAID = 'UNPAID',
}

export enum InvitationStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum YouTubeConnectionStatus {
  DISCONNECTED = 'DISCONNECTED',
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  REVOKED = 'REVOKED',
}

export enum NotificationType {
  SCAN_COMPLETED = 'SCAN_COMPLETED',
  SCAN_FAILED = 'SCAN_FAILED',
  TEAM_INVITATION = 'TEAM_INVITATION',
  USAGE_WARNING = 'USAGE_WARNING',
  BILLING_ALERT = 'BILLING_ALERT',
  SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
}

export enum AuditAction {
  USER_SIGN_IN = 'USER_SIGN_IN',
  ORGANIZATION_CREATED = 'ORGANIZATION_CREATED',
  MEMBER_INVITED = 'MEMBER_INVITED',
  MEMBER_REMOVED = 'MEMBER_REMOVED',
  MEMBER_ROLE_UPDATED = 'MEMBER_ROLE_UPDATED',
  PROJECT_CREATED = 'PROJECT_CREATED',
  SCAN_INITIATED = 'SCAN_INITIATED',
  SCAN_CANCELLED = 'SCAN_CANCELLED',
  YOUTUBE_CONNECTED = 'YOUTUBE_CONNECTED',
  YOUTUBE_DISCONNECTED = 'YOUTUBE_DISCONNECTED',
  API_KEY_ROTATED = 'API_KEY_ROTATED',
}
