import React from 'react';
import { FileText, Shield, ArrowLeft } from 'lucide-react';
import { Button } from '../components/ui/Button';
import { MarketingLayout } from '../components/marketing/MarketingLayout';
import { ROUTES } from '../router/routes';

interface PublicTermsPageProps {
  onNavigate: (route: string) => void;
}

export const PublicTermsPage: React.FC<PublicTermsPageProps> = ({ onNavigate }) => {
  return (
    <MarketingLayout
      title="Terms of Service | PreScan"
      description="PreScan Terms of Service: Guidelines, service scope, AI evaluation boundaries, and creator responsibilities."
      currentRoute={ROUTES.TERMS}
      onNavigate={onNavigate}
    >
      {/* Header */}
      <section className="py-14 sm:py-16 bg-neutral-50/80 border-b border-neutral-200/80 text-left">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 space-y-3">
          <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-neutral-200 text-neutral-800">
            <FileText className="w-3.5 h-3.5" />
            <span>Legal Agreement</span>
          </div>
          <h1 className="text-3xl font-bold tracking-tight text-neutral-900">
            Terms of Service
          </h1>
          <p className="text-xs text-neutral-500 font-mono">
            Last Updated: August 2026 • Version 1.0 (Phase 02 Baseline)
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="py-12 sm:py-16 bg-white text-left">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 space-y-10 text-xs sm:text-sm text-neutral-700 leading-relaxed">
          <div className="p-4 rounded-xl bg-amber-50/70 border border-amber-200 text-xs text-amber-900 leading-relaxed">
            <strong>Critical Policy Disclaimer:</strong> PreScan is an assistive pre-upload quality assurance tool. PreScan does not guarantee YouTube monetization, advertiser approval, copyright clearance, or absence of community guideline violations. YouTube and other third-party distribution platforms make all enforcement and monetization determinations independently. Human review is essential prior to publication.
          </div>

          <div className="space-y-3">
            <h2 className="text-base font-bold text-neutral-900">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using PreScan services, web applications, or related APIs, you agree to be bound by these Terms of Service. If you are entering into this agreement on behalf of an agency, studio, or corporate organization, you represent that you have the authority to bind that entity.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-base font-bold text-neutral-900">
              2. Scope of Service & AI Model Boundaries
            </h2>
            <p>
              PreScan provides pre-publish analysis across audio transcription, spoken dialogue heuristics, and draft metadata. You acknowledge and agree that:
            </p>
            <ul className="list-disc pl-5 space-y-1.5">
              <li>
                <strong>Assistive Function Only:</strong> Findings generated by PreScan represent automated heuristic indicators and do not constitute legal advice, copyright clearance certification, or formal policy determinations.
              </li>
              <li>
                <strong>No Content ID Matching:</strong> PreScan flags spoken and verbal mentions of third-party media. It does not perform digital fingerprinting or Content ID waveform matching.
              </li>
              <li>
                <strong>Audio & Metadata Focus:</strong> Analysis is focused on spoken audio dialogue and metadata. Visual frames are not evaluated.
              </li>
            </ul>
          </div>

          <div className="space-y-3">
            <h2 className="text-base font-bold text-neutral-900">
              3. Creator Content & Intellectual Property
            </h2>
            <p>
              You retain all right, title, and interest in and to any videos, audio recordings, titles, descriptions, and media files you submit to PreScan. You grant PreScan a limited, non-exclusive license solely to process and analyze your submitted media for the purpose of generating your evaluation reports.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-base font-bold text-neutral-900">
              4. User Responsibilities & Acceptable Use
            </h2>
            <p>
              You agree not to use PreScan to process content that violates applicable laws or to attempt to reverse engineer, disrupt, or extract underlying model parameters from the platform. You are solely responsible for all final publishing choices made on your distribution channels.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-base font-bold text-neutral-900">
              5. Disclaimers of Warranties
            </h2>
            <p>
              The service is provided on an "AS IS" and "AS AVAILABLE" basis. To the maximum extent permitted by law, PreScan disclaims all warranties, express or implied, including warranties of merchantability, fitness for a particular purpose, and non-infringement.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-base font-bold text-neutral-900">
              6. Limitation of Liability
            </h2>
            <p>
              In no event shall PreScan, its directors, or its affiliates be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of advertising revenue, channel demonetization, or platform strikes resulting from your use of the service.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-base font-bold text-neutral-900">
              7. Inquiries
            </h2>
            <p>
              Questions regarding these Terms should be directed through our{' '}
              <button
                onClick={() => onNavigate(ROUTES.CONTACT)}
                className="text-neutral-900 font-semibold underline"
              >
                Contact Form
              </button>
              .
            </p>
          </div>
        </div>
      </section>
    </MarketingLayout>
  );
};
